// ESLint 9 flat config — CommonJS (no "type":"module" in package.json)
const js = require('@eslint/js');

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        performance: 'readonly',
        localStorage: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        File: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        Image: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        fetch: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLInputElement: 'readonly',
        Element: 'readonly',
        Math: 'readonly',
        JSON: 'readonly',
        Promise: 'readonly',
        Set: 'readonly',
        Map: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Function: 'readonly',
        Symbol: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        SyntaxError: 'readonly',
        ReferenceError: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        encodeURIComponent: 'readonly',
        decodeURIComponent: 'readonly',
        structuredClone: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        screen: 'readonly',
        // canvas elements (state.js)
        canvas: 'readonly',
        ctx: 'readonly',
        nodeCanvas: 'readonly',
        nodeCtx: 'writable',
        ghostEl: 'readonly',
        // viewport (state.js)
        W: 'writable',
        H: 'writable',
        camX: 'writable',
        camY: 'writable',
        zoom: 'writable',
        time: 'writable',
        // render flags (state.js)
        gridDirty: 'writable',
        nodesDirty: 'writable',
        lastFrameTime: 'writable',
        gridCanvas: 'writable',
        // graph data (state.js)
        layers: 'writable',
        connections: 'writable',
        variables: 'writable',
        nextId: 'writable',
        nextConnSeq: 'writable',
        // selection state (state.js)
        selectedLayerId: 'writable',
        selectedConnIdx: 'writable',
        mouseDownDist: 'writable',
        mouseDownX: 'writable',
        mouseDownY: 'writable',
        lastMouseSX: 'writable',
        lastMouseSY: 'writable',
        // connection mode (state.js)
        connectionMode: 'writable',
        connectStartId: 'writable',
        connectStartSide: 'writable',
        connectMouseX: 'writable',
        connectMouseY: 'writable',
        // palette drag (state.js)
        paletteDragType: 'writable',
        paletteCustomIdx: 'writable',
        paletteDragOffset: 'writable',
        // pan/layer drag (state.js)
        panDragging: 'writable',
        panStartX: 'writable',
        panStartY: 'writable',
        panCamX: 'writable',
        panCamY: 'writable',
        layerDragging: 'writable',
        layerDragId: 'writable',
        layerDragOffX: 'writable',
        layerDragOffY: 'writable',
        layerDragOrigX: 'writable',
        layerDragOrigY: 'writable',
        // connection drag (state.js)
        connDragging: 'writable',
        connDragIdx: 'writable',
        connDragStartSX: 'writable',
        connDragStartElbowWX: 'writable',
        // clipboard (state.js)
        clipboard: 'writable',
        // superboxes (state.js)
        superboxes: 'writable',
        selectedSuperboxId: 'writable',
        drawMode: 'writable',
        sbDragging: 'writable',
        sbDragId: 'writable',
        sbDragOffX: 'writable',
        sbDragOffY: 'writable',
        sbResizing: 'writable',
        sbResizeId: 'writable',
        sbResizeEdge: 'writable',
        sbResizeStartX: 'writable',
        sbResizeStartY: 'writable',
        sbResizeOrigX: 'writable',
        sbResizeOrigY: 'writable',
        sbResizeOrigW: 'writable',
        sbResizeOrigH: 'writable',
        copiedSuperbox: 'writable',
        // visibility (state.js)
        visible: 'writable',
        // multi-select (state.js)
        selectedLayerIds: 'writable',
        selectMode: 'writable',
        groupDragging: 'writable',
        groupDragLayers: 'writable',
        groupDragOffX: 'writable',
        groupDragOffY: 'writable',
        groupDragAnchorOrigX: 'writable',
        groupDragAnchorOrigY: 'writable',
        groupDragSbs: 'writable',
        multiClipboard: 'writable',
        // FPS counter (state.js)
        _fpsEMA: 'writable',
        _fpsLastTs: 'writable',
        _fpsLastDom: 'writable',
        _hasAnimatedCache: 'writable',
        _hasAnimatedDirty: 'writable',
        // config.js globals
        layerTypes: 'readonly',
        gridSpacing: 'readonly',
        majorEvery: 'readonly',
        FRAME_MS: 'readonly',
        ALL_FNS: 'readonly',
        SUPERBOX_COLORS: 'readonly',
        SUPERBOX_COLORS_LIGHT: 'readonly',
        // shapes.js globals
        shapeCache: 'writable',
        _shapesDirty: 'writable',
        computeOutputShapes: 'readonly',
        resolveShape: 'readonly',
        getLayerShape: 'readonly',
        // utils.js globals
        resolveVal: 'readonly',
        resolveVar: 'readonly',
        evalFormula: 'readonly',
        ensureBatchVar: 'readonly',
        getDisplayShape: 'readonly',
        canConnect: 'readonly',
        hexToRgb: 'readonly',
        hash: 'readonly',
        hashF: 'readonly',
        worldToScreen: 'readonly',
        screenToWorld: 'readonly',
        snapToGrid: 'readonly',
        hitTestLayer: 'readonly',
        hitTestConnection: 'readonly',
        hitTestSuperbox: 'readonly',
        getLayerAt: 'readonly',
        getConnAt: 'readonly',
        getSuperboxAt: 'readonly',
        // renderer.js globals
        drawLayerBox: 'readonly',
        wrapText: 'readonly',
        isHologramBlocked: 'readonly',
        drawGrid: 'readonly',
        drawConnections: 'readonly',
        drawNodes: 'readonly',
        // prop-editor.js globals
        openPropEditor: 'readonly',
        closePropEditor: 'readonly',
        peBody: 'writable',
        peTitle: 'writable',
        selectedLayer: 'writable',
        // persistence.js globals
        saveState: 'readonly',
        loadState: 'readonly',
        exportToFile: 'readonly',
        importFromFile: 'readonly',
        // vars-panel.js globals
        renderVarsPanel: 'readonly',
        openVarsPanel: 'readonly',
        closeVarsPanel: 'readonly',
        // interactions.js globals
        initInteractions: 'readonly',
        // main.js globals
        animatedTypes: 'writable',
        // custom.js globals
        customLibrary: 'writable',
        validateSubnet: 'readonly',
        subnetEval: 'readonly',
        renderCustomPalette: 'readonly',
        loadCustomNnb: 'readonly',
        // internal shape engine (shapes.js)
        _connByTo: 'writable',
        _connByFrom: 'writable',
        _fanoutInnerMap: 'writable',
        _dispCache: 'writable',
        _totalParams: 'writable',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-redeclare': 'error',
      'no-console': 'off',
      'semi': ['warn', 'always'],
      'eqeqeq': ['warn', 'always', { null: 'ignore' }],
    },
    ignores: ['node_modules/'],
  },
];
